---
- name: Install RabbitMQ
  yum: name={{ item }} state=present
  with_items:
    - rabbitmq-server

- name: Start and enable RabbitMQ service
  service: name=rabbitmq-server state=started enabled=yes