- name: Copy Cassandra datastax repo file
  template: src=datastax.repo dest=/etc/yum.repos.d/
  notify:
    - yum clean

- name: Install Cassandra required packages
  yum: name={{ item }} state=present
  with_items:
    - dsc21
    - java-1.7.0-openjdk

# Update /etc/hosts required to boot Cassandra
- name: Update /etc/hosts
  lineinfile: dest=/etc/hosts regexp="^{{ ansible_default_ipv4.address }}" line='{{ ansible_default_ipv4.address }} {{ ansible_nodename }} {{ ansible_hostname }}'

- name: Applying Cassandra configuration template
  template: src=cassandra.yaml.j2 dest=/etc/cassandra/default.conf/cassandra.yaml
  notify:
    - restart cassandra

- name: Start Cassandra service
  service: name=cassandra state=started enabled=yes
