---
- name: Install curl and unzip packages
  yum: name={{ item }} state=present
  with_items:
    - curl
    - unzip

- name: Download Oracle Java 1.8 JCE package from Oracle web site
  get_url: 
    url: http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip
    dest: /tmp/jce_policy-8.zip
    headers: "Cookie:oraclelicense=accept-securebackup-cookie;"

- name: Extract Oracle Java 1.8 JCE to destination path
  unarchive:
    remote_src: True
    src: /tmp/jce_policy-8.zip
    dest: /usr/java/default/jre/lib/security/
