  - name: Install nfs and avahi packages
    yum: name={{ item }} state=present
    with_items:
      - avahi.x86_64
      - nfs-utils.x86_64
      - nfs-utils-lib.x86_64

  - name: Restart rpcbind service
    service: name=rpcbind state=restarted enabled=yes

  - name: Restart nfs service
    service: name=nfs state=restarted enabled=yes

  - name: Ensure vm_repository path exists
    file: path={{ abiquo_kvm_local_repository_path }} state=directory

  - name: Mount vm_repository share
    mount: name={{ abiquo_kvm_local_repository_path }} src={{ abiquo_kvm_remote_repository_path }} fstype=nfs opts=defaults state=mounted