---
- name: Install libselinux-python
  yum: name=libselinux-python state=present

- name: Set Disbale selinux
  selinux: conf=/etc/selinux/config policy=disabled  state=disabled  

- name: Disable selinux
  command: setenforce 0

- name: Install release rpm
  when: not abiquo_use_repos
  yum: name={{ abiquo_release_rpm }} state=present

- name: Create Base Repo
  when: abiquo_use_repos
  template: src=abiquo-base.j2 dest=/etc/yum.repos.d/abiquo-base.repo

- name: Create Updates Repo
  when: abiquo_use_repos
  template: src=abiquo-updates.j2 dest=/etc/yum.repos.d/abiquo-updates.repo

- name: Update /etc/hosts
  template: src=hosts.j2 dest=/etc/hosts
